apiVersion: kafka.mmartinlabs.com/v1alpha1
kind: KafkaTopic
metadata:
  labels:
    app.kubernetes.io/name: kafka-operator
    app.kubernetes.io/managed-by: kustomize
  name: kafkatopic-sample
spec:
  name: my-topic
  partitions: 3
  replicationFactor: 1
  config:
    cleanup.policy: compact
    retention.ms: "604800 000"
