apiVersion: kafka.mmartinlabs.com/v1alpha1
kind: KafkaTopic
metadata:
  labels:
    app.kubernetes.io/name: kafka-operator
    app.kubernetes.io/managed-by: kustomize
  name: kafkatopic-sample
spec:
  # TODO(user): Add fields here
